// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/contracts/cms.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantResolverConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PreviewSubdomainBase string                 `protobuf:"bytes,1,opt,name=preview_subdomain_base,json=previewSubdomainBase,proto3" json:"preview_subdomain_base,omitempty"`
	OnUnknownDomain      string                 `protobuf:"bytes,2,opt,name=on_unknown_domain,json=onUnknownDomain,proto3" json:"on_unknown_domain,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TenantResolverConfig) Reset() {
	*x = TenantResolverConfig{}
	mi := &file_internal_contracts_cms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResolverConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResolverConfig) ProtoMessage() {}

func (x *TenantResolverConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResolverConfig.ProtoReflect.Descriptor instead.
func (*TenantResolverConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{0}
}

func (x *TenantResolverConfig) GetPreviewSubdomainBase() string {
	if x != nil {
		return x.PreviewSubdomainBase
	}
	return ""
}

func (x *TenantResolverConfig) GetOnUnknownDomain() string {
	if x != nil {
		return x.OnUnknownDomain
	}
	return ""
}

type StaticServeBeforeDynamicConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleRoot    string                 `protobuf:"bytes,1,opt,name=bundle_root,json=bundleRoot,proto3" json:"bundle_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticServeBeforeDynamicConfig) Reset() {
	*x = StaticServeBeforeDynamicConfig{}
	mi := &file_internal_contracts_cms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticServeBeforeDynamicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticServeBeforeDynamicConfig) ProtoMessage() {}

func (x *StaticServeBeforeDynamicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticServeBeforeDynamicConfig.ProtoReflect.Descriptor instead.
func (*StaticServeBeforeDynamicConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{1}
}

func (x *StaticServeBeforeDynamicConfig) GetBundleRoot() string {
	if x != nil {
		return x.BundleRoot
	}
	return ""
}

type EngineConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Provider         string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	BundleStorage    string                 `protobuf:"bytes,2,opt,name=bundle_storage,json=bundleStorage,proto3" json:"bundle_storage,omitempty"`
	DbUrl            string                 `protobuf:"bytes,3,opt,name=db_url,json=dbUrl,proto3" json:"db_url,omitempty"`
	ContentRepoToken string                 `protobuf:"bytes,4,opt,name=content_repo_token,json=contentRepoToken,proto3" json:"content_repo_token,omitempty"`
	DefaultThemeId   string                 `protobuf:"bytes,5,opt,name=default_theme_id,json=defaultThemeId,proto3" json:"default_theme_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EngineConfig) Reset() {
	*x = EngineConfig{}
	mi := &file_internal_contracts_cms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineConfig) ProtoMessage() {}

func (x *EngineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineConfig.ProtoReflect.Descriptor instead.
func (*EngineConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{2}
}

func (x *EngineConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EngineConfig) GetBundleStorage() string {
	if x != nil {
		return x.BundleStorage
	}
	return ""
}

func (x *EngineConfig) GetDbUrl() string {
	if x != nil {
		return x.DbUrl
	}
	return ""
}

func (x *EngineConfig) GetContentRepoToken() string {
	if x != nil {
		return x.ContentRepoToken
	}
	return ""
}

func (x *EngineConfig) GetDefaultThemeId() string {
	if x != nil {
		return x.DefaultThemeId
	}
	return ""
}

type CMSAdminContributionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMSAdminContributionInput) Reset() {
	*x = CMSAdminContributionInput{}
	mi := &file_internal_contracts_cms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMSAdminContributionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMSAdminContributionInput) ProtoMessage() {}

func (x *CMSAdminContributionInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMSAdminContributionInput.ProtoReflect.Descriptor instead.
func (*CMSAdminContributionInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{3}
}

func (x *CMSAdminContributionInput) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

type CMSAdminContribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	RenderMode    string                 `protobuf:"bytes,5,opt,name=render_mode,json=renderMode,proto3" json:"render_mode,omitempty"`
	AppContext    string                 `protobuf:"bytes,6,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	Permissions   []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Actions       []string               `protobuf:"bytes,9,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMSAdminContribution) Reset() {
	*x = CMSAdminContribution{}
	mi := &file_internal_contracts_cms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMSAdminContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMSAdminContribution) ProtoMessage() {}

func (x *CMSAdminContribution) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMSAdminContribution.ProtoReflect.Descriptor instead.
func (*CMSAdminContribution) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{4}
}

func (x *CMSAdminContribution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CMSAdminContribution) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CMSAdminContribution) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CMSAdminContribution) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CMSAdminContribution) GetRenderMode() string {
	if x != nil {
		return x.RenderMode
	}
	return ""
}

func (x *CMSAdminContribution) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

func (x *CMSAdminContribution) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CMSAdminContribution) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CMSAdminContribution) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

type CMSAdminContributionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contribution  *CMSAdminContribution  `protobuf:"bytes,1,opt,name=contribution,proto3" json:"contribution,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMSAdminContributionOutput) Reset() {
	*x = CMSAdminContributionOutput{}
	mi := &file_internal_contracts_cms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMSAdminContributionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMSAdminContributionOutput) ProtoMessage() {}

func (x *CMSAdminContributionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMSAdminContributionOutput.ProtoReflect.Descriptor instead.
func (*CMSAdminContributionOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{5}
}

func (x *CMSAdminContributionOutput) GetContribution() *CMSAdminContribution {
	if x != nil {
		return x.Contribution
	}
	return nil
}

func (x *CMSAdminContributionOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AnalyticsInjectionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsInjectionConfig) Reset() {
	*x = AnalyticsInjectionConfig{}
	mi := &file_internal_contracts_cms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsInjectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsInjectionConfig) ProtoMessage() {}

func (x *AnalyticsInjectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsInjectionConfig.ProtoReflect.Descriptor instead.
func (*AnalyticsInjectionConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyticsInjectionConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type CMSRenderPageStepConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMSRenderPageStepConfig) Reset() {
	*x = CMSRenderPageStepConfig{}
	mi := &file_internal_contracts_cms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMSRenderPageStepConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMSRenderPageStepConfig) ProtoMessage() {}

func (x *CMSRenderPageStepConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMSRenderPageStepConfig.ProtoReflect.Descriptor instead.
func (*CMSRenderPageStepConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{7}
}

func (x *CMSRenderPageStepConfig) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type CMSRenderPageStepInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Subsite       string                 `protobuf:"bytes,2,opt,name=subsite,proto3" json:"subsite,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	BodyHtml      string                 `protobuf:"bytes,5,opt,name=body_html,json=bodyHtml,proto3" json:"body_html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMSRenderPageStepInput) Reset() {
	*x = CMSRenderPageStepInput{}
	mi := &file_internal_contracts_cms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMSRenderPageStepInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMSRenderPageStepInput) ProtoMessage() {}

func (x *CMSRenderPageStepInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMSRenderPageStepInput.ProtoReflect.Descriptor instead.
func (*CMSRenderPageStepInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{8}
}

func (x *CMSRenderPageStepInput) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CMSRenderPageStepInput) GetSubsite() string {
	if x != nil {
		return x.Subsite
	}
	return ""
}

func (x *CMSRenderPageStepInput) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CMSRenderPageStepInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CMSRenderPageStepInput) GetBodyHtml() string {
	if x != nil {
		return x.BodyHtml
	}
	return ""
}

type CMSRenderPageStepOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rendered      bool                   `protobuf:"varint,1,opt,name=rendered,proto3" json:"rendered,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Subsite       string                 `protobuf:"bytes,3,opt,name=subsite,proto3" json:"subsite,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Html          string                 `protobuf:"bytes,6,opt,name=html,proto3" json:"html,omitempty"`
	ContentType   string                 `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMSRenderPageStepOutput) Reset() {
	*x = CMSRenderPageStepOutput{}
	mi := &file_internal_contracts_cms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMSRenderPageStepOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMSRenderPageStepOutput) ProtoMessage() {}

func (x *CMSRenderPageStepOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMSRenderPageStepOutput.ProtoReflect.Descriptor instead.
func (*CMSRenderPageStepOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{9}
}

func (x *CMSRenderPageStepOutput) GetRendered() bool {
	if x != nil {
		return x.Rendered
	}
	return false
}

func (x *CMSRenderPageStepOutput) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CMSRenderPageStepOutput) GetSubsite() string {
	if x != nil {
		return x.Subsite
	}
	return ""
}

func (x *CMSRenderPageStepOutput) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CMSRenderPageStepOutput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CMSRenderPageStepOutput) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *CMSRenderPageStepOutput) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type CMSBundleActivateStepConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleRoot    string                 `protobuf:"bytes,1,opt,name=bundle_root,json=bundleRoot,proto3" json:"bundle_root,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMSBundleActivateStepConfig) Reset() {
	*x = CMSBundleActivateStepConfig{}
	mi := &file_internal_contracts_cms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMSBundleActivateStepConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMSBundleActivateStepConfig) ProtoMessage() {}

func (x *CMSBundleActivateStepConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMSBundleActivateStepConfig.ProtoReflect.Descriptor instead.
func (*CMSBundleActivateStepConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{10}
}

func (x *CMSBundleActivateStepConfig) GetBundleRoot() string {
	if x != nil {
		return x.BundleRoot
	}
	return ""
}

func (x *CMSBundleActivateStepConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CMSBundleActivateStepInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug    string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	TarballUrl    string                 `protobuf:"bytes,3,opt,name=tarball_url,json=tarballUrl,proto3" json:"tarball_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMSBundleActivateStepInput) Reset() {
	*x = CMSBundleActivateStepInput{}
	mi := &file_internal_contracts_cms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMSBundleActivateStepInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMSBundleActivateStepInput) ProtoMessage() {}

func (x *CMSBundleActivateStepInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMSBundleActivateStepInput.ProtoReflect.Descriptor instead.
func (*CMSBundleActivateStepInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{11}
}

func (x *CMSBundleActivateStepInput) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *CMSBundleActivateStepInput) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CMSBundleActivateStepInput) GetTarballUrl() string {
	if x != nil {
		return x.TarballUrl
	}
	return ""
}

type CMSBundleActivateStepOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activated     bool                   `protobuf:"varint,1,opt,name=activated,proto3" json:"activated,omitempty"`
	TenantSlug    string                 `protobuf:"bytes,2,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMSBundleActivateStepOutput) Reset() {
	*x = CMSBundleActivateStepOutput{}
	mi := &file_internal_contracts_cms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMSBundleActivateStepOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMSBundleActivateStepOutput) ProtoMessage() {}

func (x *CMSBundleActivateStepOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_cms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMSBundleActivateStepOutput.ProtoReflect.Descriptor instead.
func (*CMSBundleActivateStepOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_cms_proto_rawDescGZIP(), []int{12}
}

func (x *CMSBundleActivateStepOutput) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *CMSBundleActivateStepOutput) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *CMSBundleActivateStepOutput) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CMSBundleActivateStepOutput) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

var File_internal_contracts_cms_proto protoreflect.FileDescriptor

const file_internal_contracts_cms_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/contracts/cms.proto\x12\x17workflow.plugins.cms.v1\"x\n" +
	"\x14TenantResolverConfig\x124\n" +
	"\x16preview_subdomain_base\x18\x01 \x01(\tR\x14previewSubdomainBase\x12*\n" +
	"\x11on_unknown_domain\x18\x02 \x01(\tR\x0fonUnknownDomain\"A\n" +
	"\x1eStaticServeBeforeDynamicConfig\x12\x1f\n" +
	"\vbundle_root\x18\x01 \x01(\tR\n" +
	"bundleRoot\"\xc0\x01\n" +
	"\fEngineConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12%\n" +
	"\x0ebundle_storage\x18\x02 \x01(\tR\rbundleStorage\x12\x15\n" +
	"\x06db_url\x18\x03 \x01(\tR\x05dbUrl\x12,\n" +
	"\x12content_repo_token\x18\x04 \x01(\tR\x10contentRepoToken\x12(\n" +
	"\x10default_theme_id\x18\x05 \x01(\tR\x0edefaultThemeId\";\n" +
	"\x19CMSAdminContributionInput\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\"\x80\x03\n" +
	"\x14CMSAdminContribution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1f\n" +
	"\vrender_mode\x18\x05 \x01(\tR\n" +
	"renderMode\x12\x1f\n" +
	"\vapp_context\x18\x06 \x01(\tR\n" +
	"appContext\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\x12W\n" +
	"\bmetadata\x18\b \x03(\v2;.workflow.plugins.cms.v1.CMSAdminContribution.MetadataEntryR\bmetadata\x12\x18\n" +
	"\aactions\x18\t \x03(\tR\aactions\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x1aCMSAdminContributionOutput\x12Q\n" +
	"\fcontribution\x18\x01 \x01(\v2-.workflow.plugins.cms.v1.CMSAdminContributionR\fcontribution\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\".\n" +
	"\x18AnalyticsInjectionConfig\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\"<\n" +
	"\x17CMSRenderPageStepConfig\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\"\x96\x01\n" +
	"\x16CMSRenderPageStepInput\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x18\n" +
	"\asubsite\x18\x02 \x01(\tR\asubsite\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1b\n" +
	"\tbody_html\x18\x05 \x01(\tR\bbodyHtml\"\xcd\x01\n" +
	"\x17CMSRenderPageStepOutput\x12\x1a\n" +
	"\brendered\x18\x01 \x01(\bR\brendered\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x18\n" +
	"\asubsite\x18\x03 \x01(\tR\asubsite\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04html\x18\x06 \x01(\tR\x04html\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\"T\n" +
	"\x1bCMSBundleActivateStepConfig\x12\x1f\n" +
	"\vbundle_root\x18\x01 \x01(\tR\n" +
	"bundleRoot\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"x\n" +
	"\x1aCMSBundleActivateStepInput\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vtarball_url\x18\x03 \x01(\tR\n" +
	"tarballUrl\"\x8e\x01\n" +
	"\x1bCMSBundleActivateStepOutput\x12\x1c\n" +
	"\tactivated\x18\x01 \x01(\bR\tactivated\x12\x1f\n" +
	"\vtenant_slug\x18\x02 \x01(\tR\n" +
	"tenantSlug\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256BIZGgithub.com/GoCodeAlone/workflow-plugin-cms/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_cms_proto_rawDescOnce sync.Once
	file_internal_contracts_cms_proto_rawDescData []byte
)

func file_internal_contracts_cms_proto_rawDescGZIP() []byte {
	file_internal_contracts_cms_proto_rawDescOnce.Do(func() {
		file_internal_contracts_cms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_cms_proto_rawDesc), len(file_internal_contracts_cms_proto_rawDesc)))
	})
	return file_internal_contracts_cms_proto_rawDescData
}

var file_internal_contracts_cms_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_contracts_cms_proto_goTypes = []any{
	(*TenantResolverConfig)(nil),           // 0: workflow.plugins.cms.v1.TenantResolverConfig
	(*StaticServeBeforeDynamicConfig)(nil), // 1: workflow.plugins.cms.v1.StaticServeBeforeDynamicConfig
	(*EngineConfig)(nil),                   // 2: workflow.plugins.cms.v1.EngineConfig
	(*CMSAdminContributionInput)(nil),      // 3: workflow.plugins.cms.v1.CMSAdminContributionInput
	(*CMSAdminContribution)(nil),           // 4: workflow.plugins.cms.v1.CMSAdminContribution
	(*CMSAdminContributionOutput)(nil),     // 5: workflow.plugins.cms.v1.CMSAdminContributionOutput
	(*AnalyticsInjectionConfig)(nil),       // 6: workflow.plugins.cms.v1.AnalyticsInjectionConfig
	(*CMSRenderPageStepConfig)(nil),        // 7: workflow.plugins.cms.v1.CMSRenderPageStepConfig
	(*CMSRenderPageStepInput)(nil),         // 8: workflow.plugins.cms.v1.CMSRenderPageStepInput
	(*CMSRenderPageStepOutput)(nil),        // 9: workflow.plugins.cms.v1.CMSRenderPageStepOutput
	(*CMSBundleActivateStepConfig)(nil),    // 10: workflow.plugins.cms.v1.CMSBundleActivateStepConfig
	(*CMSBundleActivateStepInput)(nil),     // 11: workflow.plugins.cms.v1.CMSBundleActivateStepInput
	(*CMSBundleActivateStepOutput)(nil),    // 12: workflow.plugins.cms.v1.CMSBundleActivateStepOutput
	nil,                                    // 13: workflow.plugins.cms.v1.CMSAdminContribution.MetadataEntry
}
var file_internal_contracts_cms_proto_depIdxs = []int32{
	13, // 0: workflow.plugins.cms.v1.CMSAdminContribution.metadata:type_name -> workflow.plugins.cms.v1.CMSAdminContribution.MetadataEntry
	4,  // 1: workflow.plugins.cms.v1.CMSAdminContributionOutput.contribution:type_name -> workflow.plugins.cms.v1.CMSAdminContribution
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_contracts_cms_proto_init() }
func file_internal_contracts_cms_proto_init() {
	if File_internal_contracts_cms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_cms_proto_rawDesc), len(file_internal_contracts_cms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_cms_proto_goTypes,
		DependencyIndexes: file_internal_contracts_cms_proto_depIdxs,
		MessageInfos:      file_internal_contracts_cms_proto_msgTypes,
	}.Build()
	File_internal_contracts_cms_proto = out.File
	file_internal_contracts_cms_proto_goTypes = nil
	file_internal_contracts_cms_proto_depIdxs = nil
}
